Vagrant.configure('2') do |config|
  vm_name = "configh-#{`hg branch`.strip}-ci".gsub(/[^a-zA-Z\-\d.]/, '-')
  config.vm.hostname = vm_name

  config.vm.box = vm_name
  config.vm.box_url = 'file:///var/vagrant_boxes/armagh-ci.box'

  config.vm.provider 'virtualbox' do |v|
    v.name = vm_name
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.provision 'file', source: '~/.bundle/config', destination: '.bundle/config'

  config.vm.provision 'shell', inline: <<-SHELL
  echo 'export GEM_HOME=$HOME/.gem'    >> /etc/profile.d/rubygems.sh
  echo 'export GEM_PATH=$HOME/.gem'    >> /etc/profile.d/rubygems.sh
  echo 'export PATH=$GEM_PATH/bin:$PATH' >> /etc/profile.d/rubygems.sh
  echo 'export DBUS_SESSION_BUS_ADDRESS=""' >> /etc/profile.d/test_env.sh
  echo 'export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib:$LD_LIBRARY_PATH' >> /etc/profile.d/oracle.sh
  mkdir -p /var/log/armagh
  chown vagrant.vagrant /var/log/armagh
  mkdir -p /data/db
  chown vagrant.vagrant /data/db
  SHELL

  config.vm.synced_folder '../../', '/workspace'

end
